const ingredientData = window.COOKLIKEME_INGREDIENTS || {};
const recipes = Array.isArray(window.COOKLIKEME_RECIPES) ? window.COOKLIKEME_RECIPES : [];
let activeMode = "regular";
let selectedIngredients = [];
try { selectedIngredients = JSON.parse(localStorage.getItem("cookLikeMe_selectedIngredients") || "[]"); if (!Array.isArray(selectedIngredients)) selectedIngredients = []; } catch { selectedIngredients = []; }
const $ = id => document.getElementById(id);
const modeTabs=$("modeTabs"),ingredientGroupsEl=$("ingredientGroups"),selectedIngredientsEl=$("selectedIngredients"),selectedCount=$("selectedCount"),customIngredientInput=$("customIngredientInput"),addCustomIngredientBtn=$("addCustomIngredientBtn"),clearIngredientsBtn=$("clearIngredientsBtn"),findMealsBtn=$("findMealsBtn"),surpriseBtn=$("surpriseBtn"),bestMatchEl=$("bestMatch"),resultsGrid=$("resultsGrid"),resultCount=$("resultCount"),recipeModal=$("recipeModal"),recipeModalBackdrop=$("recipeModalBackdrop"),recipeModalContent=$("recipeModalContent"),closeRecipeModal=$("closeRecipeModal");
const kitchenReadoutTitle=$("kitchenReadoutTitle"),comboStrength=$("comboStrength"),readoutProtein=$("readoutProtein"),readoutBase=$("readoutBase"),readoutSide=$("readoutSide"),readoutFlavor=$("readoutFlavor"),kitchenReadoutMessage=$("kitchenReadoutMessage");
function normalize(v){return String(v||"").trim().toLowerCase()}
function titleCase(v){return normalize(v).split(" ").map(w=>w.charAt(0).toUpperCase()+w.slice(1)).join(" ")}
function saveSelected(){localStorage.setItem("cookLikeMe_selectedIngredients",JSON.stringify(selectedIngredients))}
const families=[["chicken","chicken breast","chicken thighs","chicken wings","fried chicken","ground chicken"],["turkey","ground turkey","turkey sausage"],["ground beef","steak","lean steak","beef strips","chuck roast","short ribs"],["pork chops","pork tenderloin","pulled pork"],["sausage","italian sausage","smoked sausage"],["fish","tilapia","cod","catfish"],["rice","white rice","yellow rice","brown rice","jasmine rice","basmati rice","rice and peas"],["pasta","spaghetti","penne","fettuccine","linguine","ziti","macaroni","egg noodles","whole wheat pasta"],["potatoes","red potatoes","roasted potatoes","mashed potatoes","sweet potato"],["tortilla","flour tortilla","corn tortilla","whole wheat tortilla","wrap"]];
function sameIngredient(a,b){a=normalize(a);b=normalize(b);if(a===b)return true;return families.some(g=>g.includes(a)&&g.includes(b))}
function userHas(i){return selectedIngredients.some(x=>sameIngredient(x,i))}
const proteins=new Set(["chicken","chicken breast","chicken thighs","chicken wings","fried chicken","ground chicken","turkey","ground turkey","turkey sausage","ground beef","steak","lean steak","beef strips","chuck roast","short ribs","pork chops","pork tenderloin","pulled pork","bacon","sausage","italian sausage","smoked sausage","lamb chops","shrimp","salmon","fish","tilapia","cod","catfish","tuna","crab","crab meat","scallops","eggs","egg whites","tofu"]);
const bases=new Set(["rice","white rice","yellow rice","brown rice","jasmine rice","basmati rice","rice and peas","pasta","spaghetti","penne","fettuccine","linguine","ziti","macaroni","egg noodles","whole wheat pasta","potatoes","red potatoes","sweet potato","roasted potatoes","mashed potatoes","fries","sweet potato fries","grits","quinoa","beans","black beans","kidney beans","red beans","chickpeas","plantain","bread","white bread","wheat bread","brioche","rolls","tortilla","flour tortilla","corn tortilla","whole wheat tortilla","wrap","oats"]);
const flavors=new Set(["gravy","brown gravy","chicken gravy","hot sauce","buffalo sauce","bbq sauce","soy sauce","low sodium soy sauce","teriyaki sauce","worcestershire sauce","alfredo sauce","tomato sauce","marinara","garlic butter","honey garlic sauce","jerk sauce","brown stew sauce","coconut milk","coconut cream","ranch","mayo","mustard","ketchup","honey","olive oil","lime","lime juice","lemon","lemon juice"]);
const recipeOnlySeasonings=new Set(["salt","sea salt","black pepper","white pepper","garlic powder","onion powder","paprika","smoked paprika","cajun seasoning","creole seasoning","old bay","seasoned salt","adobo","sazon","lemon pepper","italian seasoning","oregano","basil seasoning","parsley seasoning","rosemary seasoning","thyme seasoning","red pepper flakes","cayenne pepper","chili powder","cumin","curry powder","caribbean curry powder","jerk seasoning","allspice","brown sugar","cinnamon","nutmeg"]);
function roleOf(i){const v=normalize(i);if(proteins.has(v))return"protein";if(bases.has(v))return"base";if(flavors.has(v))return"flavor";if(recipeOnlySeasonings.has(v))return"seasoning";return"support"}
function selectedByRole(r){return selectedIngredients.filter(i=>roleOf(i)===r)}
function firstByRole(r){return selectedByRole(r)[0]||""}
function bestSide(){return selectedIngredients.find(i=>roleOf(i)==="support")||""}
function formatMode(m){return{regular:"Food",healthy:"Healthy",shakes:"Shakes & Smoothies",drinks:"Drinks",desserts:"Desserts"}[m]||titleCase(m)}
function modeFromUrl(){const m=new URLSearchParams(location.search).get("mode");if(ingredientData[m])activeMode=m}
function setMode(m){if(!ingredientData[m])return;activeMode=m;document.querySelectorAll(".mode-tab").forEach(t=>t.classList.toggle("active",t.dataset.mode===m));renderIngredientGroups();renderSelectedIngredients();renderKitchenReadout();renderEmptyResults()}
function renderIngredientGroups(){ingredientGroupsEl.innerHTML="";const groups=ingredientData[activeMode];if(!groups||typeof groups!=="object"){ingredientGroupsEl.innerHTML='<div class="finder-empty">Ingredient list could not load.</div>';return}Object.entries(groups).forEach(([name,items])=>{const s=document.createElement("section");s.className="ingredient-group";const h=document.createElement("h3");h.textContent=name;const buttons=document.createElement("div");buttons.className="ingredient-buttons";(items||[]).forEach(i=>{const b=document.createElement("button");b.type="button";b.className="ingredient-btn";b.textContent=i;b.classList.toggle("active",selectedIngredients.includes(normalize(i)));b.addEventListener("click",()=>toggleIngredient(i));buttons.appendChild(b)});s.append(h,buttons);ingredientGroupsEl.appendChild(s)})}
function renderSelectedIngredients(){selectedIngredientsEl.innerHTML="";selectedCount.textContent=`${selectedIngredients.length} ${selectedIngredients.length===1?"ingredient":"ingredients"}`;if(!selectedIngredients.length){selectedIngredientsEl.innerHTML='<span class="selected-empty">Nothing selected yet.</span>';return}selectedIngredients.forEach(i=>{const tag=document.createElement("span");tag.className="selected-tag";tag.innerHTML=`${i} <button type="button" aria-label="Remove ${i}">×</button>`;tag.querySelector("button").addEventListener("click",()=>{selectedIngredients=selectedIngredients.filter(x=>x!==i);refreshPicker()});selectedIngredientsEl.appendChild(tag)})}
function refreshPicker(){saveSelected();renderSelectedIngredients();renderIngredientGroups();renderKitchenReadout()}
function toggleIngredient(i){const v=normalize(i);selectedIngredients=selectedIngredients.includes(v)?selectedIngredients.filter(x=>x!==v):[...selectedIngredients,v];refreshPicker()}
function addCustomIngredient(){const v=normalize(customIngredientInput.value);if(!v)return;if(!selectedIngredients.includes(v))selectedIngredients.push(v);customIngredientInput.value="";refreshPicker()}
function renderKitchenReadout(){if(!selectedIngredients.length){readoutProtein.textContent="Not picked";readoutBase.textContent="Not picked";readoutSide.textContent="Not picked";readoutFlavor.textContent="Not picked";kitchenReadoutTitle.textContent="Start building your combo.";comboStrength.textContent="Waiting";comboStrength.className="combo-strength neutral";kitchenReadoutMessage.textContent="Pick a few main ingredients and CookLikeMe will start reading the plate.";return}if(!["regular","healthy"].includes(activeMode)){readoutProtein.textContent=titleCase(selectedIngredients[0]||"Not picked");readoutBase.textContent=titleCase(selectedIngredients[1]||"Not picked");readoutSide.textContent=titleCase(selectedIngredients[2]||"Not picked");readoutFlavor.textContent=titleCase(selectedIngredients[3]||"Not picked");kitchenReadoutTitle.textContent=`${selectedIngredients.length} ingredients selected.`;comboStrength.textContent=selectedIngredients.length>=3?"Ready":"Keep Going";comboStrength.className=`combo-strength ${selectedIngredients.length>=3?"strong":"good"}`;kitchenReadoutMessage.textContent="Hit Find My Best Move when you’re ready.";return}const p=firstByRole("protein"),b=firstByRole("base"),s=bestSide(),f=firstByRole("flavor");readoutProtein.textContent=p?titleCase(p):"Not picked";readoutBase.textContent=b?titleCase(b):"Not picked";readoutSide.textContent=s?titleCase(s):"Not picked";readoutFlavor.textContent=f?titleCase(f):"Not picked";let strength=(p?2:0)+(b?1:0)+(s?1:0)+(f?1:0);if(p&&b&&(s||f)){kitchenReadoutTitle.textContent="That’s looking like a real meal.";comboStrength.textContent=strength>=5?"Strong Combo":"Good Combo";comboStrength.className=`combo-strength ${strength>=5?"strong":"good"}`;kitchenReadoutMessage.textContent="You’ve got enough for CookLikeMe to give you a strong direction."}else if(p){kitchenReadoutTitle.textContent=`${titleCase(p)} is the main move.`;comboStrength.textContent="Getting There";comboStrength.className="combo-strength good";kitchenReadoutMessage.textContent="Add a base, side, or sauce to make the recommendation sharper."}else{kitchenReadoutTitle.textContent="Pick a main protein if you have one.";comboStrength.textContent="Needs More";comboStrength.className="combo-strength weak";kitchenReadoutMessage.textContent="CookLikeMe can still suggest ideas, but a main ingredient will make the result much better."}}
function scoreRecipe(r){const core=r.coreIngredients||[],flavor=r.flavorIngredients||[],optional=r.optionalIngredients||[];let score=0;const missingMain=[],matchedMain=[],missingOther=[];core.forEach(i=>{const role=roleOf(i),matched=userHas(i);if(role==="seasoning"){if(matched)score+=1;return}if(role==="protein"){if(matched){score+=50;matchedMain.push(i)}else{score-=70;missingMain.push(i)}return}if(role==="base"){if(matched){score+=24;matchedMain.push(i)}else{score-=12;missingOther.push(i)}return}if(role==="flavor"){score+=matched?18:-2;return}if(matched)score+=10;else missingOther.push(i)});flavor.forEach(i=>{if(roleOf(i)!=="seasoning"&&userHas(i))score+=roleOf(i)==="flavor"?10:5});optional.forEach(i=>{if(userHas(i))score+=2});const p=firstByRole("protein"),b=firstByRole("base"),f=firstByRole("flavor");if(p&&core.some(i=>roleOf(i)==="protein"&&userHas(i)))score+=25;if(b&&core.some(i=>roleOf(i)==="base"&&userHas(i)))score+=12;if(f&&[...core,...flavor].some(i=>roleOf(i)==="flavor"&&userHas(i)))score+=10;return{score,missingMain,missingOther,matchedMain}}
function getSeasoningSuggestion(protein,flavor){const p=normalize(protein),f=normalize(flavor);if(f.includes("jerk"))return["jerk seasoning","garlic powder","onion powder","thyme","black pepper"];if(f.includes("brown stew"))return["seasoned salt","garlic powder","onion powder","paprika","thyme"];if(f.includes("alfredo")||f.includes("marinara"))return["garlic powder","black pepper","italian seasoning"];if(f.includes("buffalo")||f.includes("bbq")||f.includes("honey garlic"))return["garlic powder","onion powder","smoked paprika","black pepper"];if(f.includes("coconut"))return["curry powder","garlic powder","onion powder","thyme"];if(p.includes("shrimp")||p.includes("fish")||p.includes("salmon")||p.includes("tilapia"))return["old bay","garlic powder","paprika","black pepper"];if(p.includes("steak")||p.includes("beef")||p.includes("lamb"))return["seasoned salt","garlic powder","onion powder","black pepper"];return["seasoned salt","garlic powder","onion powder","paprika","black pepper"]}
function smartPlate(){if(!["regular","healthy"].includes(activeMode))return null;const protein=firstByRole("protein"),base=firstByRole("base"),side=bestSide(),flavor=firstByRole("flavor");if(!protein||(!base&&!side&&!flavor))return null;const seasonings=getSeasoningSuggestion(protein,flavor),p=titleCase(protein),b=titleCase(base),s=titleCase(side);let title=`${p}${base?` with ${b}`:""}${side?` & ${s}`:""}`;if(flavor==="honey garlic sauce")title=`Honey Garlic ${p}${base?` with ${b}`:""}${side?` & ${s}`:""}`;else if(flavor==="jerk sauce")title=`Jerk ${p}${base?` with ${b}`:""}${side?` & ${s}`:""}`;else if(flavor==="garlic butter")title=`Garlic Butter ${p}${base?` with ${b}`:""}`;else if(flavor==="buffalo sauce")title=`Buffalo ${p}${base?` with ${b}`:""}`;else if(flavor==="bbq sauce")title=`BBQ ${p}${base?` with ${b}`:""}`;else if(flavor==="brown stew sauce")title=`Brown Stew ${p}${base?` with ${b}`:""}`;else if(flavor==="alfredo sauce")title=`Creamy ${p} Alfredo`;const ingredientList=[protein,base,side,flavor].filter(Boolean);return{id:`smart-${Date.now()}`,mode:activeMode,title,category:"CookLikeMe Pick",tags:["Smart Plate"],time:"25–40 min",prepTime:"10 min",cookTime:"20–30 min",servings:2,difficulty:"Easy",ingredients:ingredientList.map(item=>({item,amount:"Use what you have"})),coreIngredients:[protein,base,side].filter(Boolean),flavorIngredients:[flavor].filter(Boolean),optionalIngredients:[],description:`${p}${flavor?` finished with ${titleCase(flavor)}`:""}${base?`, served with ${b}`:""}${side?` and ${s}`:""}. CookLikeMe recommends ${seasonings.map(titleCase).join(", ")} to season it.`,instructions:[`Season the ${protein} with ${seasonings.join(", ")}.`,`Cook the ${protein} until browned and fully cooked.`,base?`Prepare the ${base}.`:null,side?`Cook or season the ${side} as your side.`:null,flavor?`Finish with ${flavor}.`:null,"Taste, adjust, and serve everything hot."].filter(Boolean),recommendedSeasonings:seasonings,isSmartPlate:true}}
function renderEmptyResults(){bestMatchEl.innerHTML='<div class="finder-empty">Pick ingredients, then hit <strong>Find My Best Move</strong>.</div>';resultsGrid.innerHTML='<div class="finder-empty">Other strong ideas will show here.</div>';resultCount.textContent="0 results"}
function findMeals(){if(!selectedIngredients.length){renderEmptyResults();bestMatchEl.innerHTML='<div class="finder-empty">Pick at least one ingredient first.</div>';return}const ranked=recipes.filter(r=>r.mode===activeMode).map(recipe=>({recipe,match:scoreRecipe(recipe)})).sort((a,b)=>b.match.score-a.match.score),smart=smartPlate(),best=ranked[0],smartShouldLead=smart&&(!best||best.match.score<65||best.match.missingMain.length>0);if(smartShouldLead)renderBestCard(smart,{label:"🔥 CookLikeMe Pick",explanation:"Built directly from the food you selected.",missing:[]});else if(best&&best.match.score>0){const missing=[...best.match.missingMain,...best.match.missingOther];renderBestCard(best.recipe,{label:best.match.score>=100?"🔥 Damn Good Match":best.match.score>=65?"Strong Match":"Good Idea",explanation:best.match.missingMain.length?"This is close, but you’re missing a main ingredient.":"The important parts of this meal line up with what you have.",missing})}else bestMatchEl.innerHTML='<div class="finder-empty">Nothing strong enough yet. Add another main ingredient and try again.</div>';renderOtherResults(ranked);$("resultsSection").scrollIntoView({behavior:"smooth"})}
function renderBestCard(recipe,meta){bestMatchEl.innerHTML=`<article class="best-match-card"><div class="recipe-topline"><span class="match-label">${meta.label}</span><span class="mode-label">${formatMode(recipe.mode)}</span></div><h3>${recipe.title}</h3><p>${recipe.description||""}</p><div class="recipe-meta">${recipe.category?`<span class="meta-pill">${recipe.category}</span>`:""}${recipe.time?`<span class="meta-pill">${recipe.time}</span>`:""}${recipe.difficulty?`<span class="meta-pill">${recipe.difficulty}</span>`:""}</div><p class="missing-line"><strong>Why this works:</strong> ${meta.explanation}</p>${meta.missing.length?`<p class="missing-line">Missing: ${meta.missing.slice(0,4).map(titleCase).join(", ")}</p>`:""}<div class="recipe-actions"><button class="recipe-action-btn primary" id="bestViewRecipe">View Recipe</button><button class="recipe-action-btn" id="bestSaveRecipe">Save ♥</button></div></article>`;$("bestViewRecipe").addEventListener("click",()=>openRecipeModal(recipe));$("bestSaveRecipe").addEventListener("click",()=>saveRecipe(recipe))}
function renderOtherResults(ranked){const visible=ranked.filter(i=>i.match.score>15&&i.match.missingMain.length===0).slice(0,9);resultCount.textContent=`${visible.length} ${visible.length===1?"result":"results"}`;resultsGrid.innerHTML="";if(!visible.length){resultsGrid.innerHTML='<div class="finder-empty">No other strong recipe matches yet.</div>';return}visible.forEach(({recipe,match})=>{const card=document.createElement("article"),missing=match.missingOther.slice(0,3);card.className="recipe-card";card.innerHTML=`<div class="recipe-topline"><span class="match-label">${match.score>=65?"Strong Match":"Good Idea"}</span><span class="mode-label">${formatMode(recipe.mode)}</span></div><h3>${recipe.title}</h3><p>${recipe.description||""}</p><div class="recipe-meta">${recipe.time?`<span class="meta-pill">${recipe.time}</span>`:""}${recipe.difficulty?`<span class="meta-pill">${recipe.difficulty}</span>`:""}</div>${missing.length?`<p class="missing-line">Missing: ${missing.map(titleCase).join(", ")}</p>`:'<p class="missing-line">You’ve got the important stuff.</p>'}<div class="recipe-actions"><button class="recipe-action-btn primary view-recipe">View Recipe</button><button class="recipe-action-btn save-recipe">Save ♥</button></div>`;card.querySelector(".view-recipe").addEventListener("click",()=>openRecipeModal(recipe));card.querySelector(".save-recipe").addEventListener("click",()=>saveRecipe(recipe));resultsGrid.appendChild(card)})}
function surpriseMe(){const r=recipes.filter(x=>x.mode===activeMode);if(r.length)openRecipeModal(r[Math.floor(Math.random()*r.length)])}
function saveRecipe(recipe){let saved=[];try{saved=JSON.parse(localStorage.getItem("cookLikeMe_savedRecipes")||"[]");if(!Array.isArray(saved))saved=[]}catch{saved=[]}if(!saved.some(i=>i.id===recipe.id)){saved.push(recipe);localStorage.setItem("cookLikeMe_savedRecipes",JSON.stringify(saved));alert(`${recipe.title} saved.`)}else alert(`${recipe.title} is already saved.`)}
function startCooking(recipe){localStorage.setItem("cookLikeMe_activeRecipe",JSON.stringify(recipe));location.href="cook.html"}
function openRecipeModal(recipe){const q=Array.isArray(recipe.ingredients)?recipe.ingredients:[],fallback=[...(recipe.coreIngredients||[]),...(recipe.flavorIngredients||[]),...(recipe.optionalIngredients||[])];recipeModalContent.innerHTML=`<p class="modal-category">${formatMode(recipe.mode)}${recipe.category?` • ${recipe.category}`:""}</p><h2>${recipe.title}</h2><p class="modal-description">${recipe.description||""}</p><div class="recipe-meta">${recipe.prepTime?`<span class="meta-pill">Prep ${recipe.prepTime}</span>`:""}${recipe.cookTime?`<span class="meta-pill">Cook ${recipe.cookTime}</span>`:""}${recipe.servings?`<span class="meta-pill">Serves ${recipe.servings}</span>`:""}${recipe.difficulty?`<span class="meta-pill">${recipe.difficulty}</span>`:""}</div><section class="modal-section"><h3>What You Need</h3><ul class="modal-list">${q.length?q.map(e=>typeof e==="string"?`<li>${titleCase(e)}</li>`:`<li><strong>${e.amount||""}</strong> ${titleCase(e.item||"")}</li>`).join(""):fallback.map(i=>`<li>${titleCase(i)}</li>`).join("")}</ul></section>${Array.isArray(recipe.recommendedSeasonings)&&recipe.recommendedSeasonings.length?`<section class="modal-section"><h3>Make It Hit 🔥</h3><p class="modal-description">CookLikeMe suggests ${recipe.recommendedSeasonings.map(titleCase).join(", ")}. Season it your way if you already have a blend you like.</p></section>`:""}<section class="modal-section"><h3>How It Comes Together</h3><ol class="modal-list">${(recipe.instructions||[]).map(s=>`<li>${s}</li>`).join("")}</ol></section><div class="recipe-actions"><button id="modalCookRecipe" class="recipe-action-btn primary">Start Cooking →</button><button id="modalSaveRecipe" class="recipe-action-btn">Save ♥</button></div>`;recipeModal.classList.remove("hidden");$("modalCookRecipe").addEventListener("click",()=>startCooking(recipe));$("modalSaveRecipe").addEventListener("click",()=>saveRecipe(recipe))}
function closeModal(){recipeModal.classList.add("hidden")}
modeTabs.addEventListener("click",e=>{const b=e.target.closest(".mode-tab");if(b)setMode(b.dataset.mode)});addCustomIngredientBtn.addEventListener("click",addCustomIngredient);customIngredientInput.addEventListener("keydown",e=>{if(e.key==="Enter")addCustomIngredient()});clearIngredientsBtn.addEventListener("click",()=>{selectedIngredients=[];refreshPicker();renderEmptyResults()});findMealsBtn.addEventListener("click",findMeals);surpriseBtn.addEventListener("click",surpriseMe);closeRecipeModal.addEventListener("click",closeModal);recipeModalBackdrop.addEventListener("click",closeModal);document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});function init(){modeFromUrl();setMode(activeMode)}init();